INSERT INTO lingue (codice, descrizione) VALUES ('AR', 'Arabic');
INSERT INTO lingue (codice, descrizione) VALUES ('BG', 'Bulgarian');
INSERT INTO lingue (codice, descrizione) VALUES ('CS', 'Czech');
INSERT INTO lingue (codice, descrizione) VALUES ('DA', 'Danish');
INSERT INTO lingue (codice, descrizione) VALUES ('DE', 'German');
INSERT INTO lingue (codice, descrizione) VALUES ('EL', 'Greek');
INSERT INTO lingue (codice, descrizione) VALUES ('EN-GB', 'English (British)');
INSERT INTO lingue (codice, descrizione) VALUES ('EN-US', 'English (American)');
INSERT INTO lingue (codice, descrizione) VALUES ('ES', 'Spanish');
INSERT INTO lingue (codice, descrizione) VALUES ('ET', 'Estonian');
INSERT INTO lingue (codice, descrizione) VALUES ('FI', 'Finnish');
INSERT INTO lingue (codice, descrizione) VALUES ('FR', 'French');
INSERT INTO lingue (codice, descrizione) VALUES ('HU', 'Hungarian');
INSERT INTO lingue (codice, descrizione) VALUES ('ID', 'Indonesian');
INSERT INTO lingue (codice, descrizione) VALUES ('IT', 'Italian');
INSERT INTO lingue (codice, descrizione) VALUES ('JA', 'Japanese');
INSERT INTO lingue (codice, descrizione) VALUES ('KO', 'Korean');
INSERT INTO lingue (codice, descrizione) VALUES ('LT', 'Lithuanian');
INSERT INTO lingue (codice, descrizione) VALUES ('LV', 'Latvian');
INSERT INTO lingue (codice, descrizione) VALUES ('NB', 'Norwegian');
INSERT INTO lingue (codice, descrizione) VALUES ('NL', 'Dutch');
INSERT INTO lingue (codice, descrizione) VALUES ('PL', 'Polish');
INSERT INTO lingue (codice, descrizione) VALUES ('PT-BR', 'Portuguese (Brazilian)');
INSERT INTO lingue (codice, descrizione) VALUES ('PT-PT', 'Portuguese (European)');
INSERT INTO lingue (codice, descrizione) VALUES ('RO', 'Romanian');
INSERT INTO lingue (codice, descrizione) VALUES ('RU', 'Russian');
INSERT INTO lingue (codice, descrizione) VALUES ('SK', 'Slovak');
INSERT INTO lingue (codice, descrizione) VALUES ('SL', 'Slovenian');
INSERT INTO lingue (codice, descrizione) VALUES ('SV', 'Swedish');
INSERT INTO lingue (codice, descrizione) VALUES ('TR', 'Turkish');
INSERT INTO lingue (codice, descrizione) VALUES ('UK', 'Ukrainian');
INSERT INTO lingue (codice, descrizione) VALUES ('ZH-HA','Chinese (simplified)');
-- INSERT INTO lingue (codice, descrizione) VALUES ('ZH-HA','Chinese (traditional)');
commit;